### ISSUE TITLE
make more self contained...

### ISSUE THREAD

**Issue by acinader** [montymxb/parse-server-test#1]
using `npm -g` and `npm -g update` is invasive for folks doing node dev on the same machine.

I'm just barely getting started here, so take with big grain of salt, but seems like you could have a package.json with mongodb-runner and parse-server as dependencies and then an npm start script that could run the whole thing.  then this repo would be standard in that you could clone it, run npm intall and then npm start and you'd be in biz.

feel free to close.  just chatting ;).  If i get traction, i'll give it a try....

**Comment by montymxb** [comment]
@acinader I agree! That would be a more appealing approach as opposed to the current global install. This was quickly implemented to provide a standalone means for getting a local test environment up and running quickly, but a bit dirty I must admit.

I'll add a ```package.json``` file to help keep this nicely isolated.

**Comment by montymxb** [comment]
I made a few adjustments but [this commit](https://github.com/montymxb/parse-server-test/commit/d6aa4be37966e335f76bf7e5a932268652db965b) introduces changes to use a proper package.json and to install the dependencies locally. Now a straight forward ```npm install``` & ```npm start``` will get you off and running! Additionally after installing you may still call ```./run-server``` if you wish, ```npm start``` just calls this for you.

At some point I may setup an index.js file to run parse-server via node instead of from the command line ```parse-server```. I'll wait to see if it will be needed though.

Thanks again for your suggestions 👍 .

**Comment by acinader** [comment]
nice.  looks good.
